enable-module-update = true
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config


[YouTube]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Custom branding' 'Enable debugging'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#181825"

[YouTube-Oreo]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
version = "20.26.46"
excluded-patches = "'Custom branding' 'Enable debugging'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#181825"

[Music]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
excluded-patches = "'Custom branding' 'Enable debugging'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#181825"

[Cloudflare-1111]
app-name = "1.1.1.1"
build-mode = "apk"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
version = "auto"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"

[BlockBlast]
app-name = "Block Blast!"
build-mode = "apk"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
version = "auto"
uptodown-dlurl = "https://block-blast-adventure-master.en.uptodown.com/android"

[Boorusama]
app-name = "Boorusama"
build-mode = "apk"
patches-source = "kiraio-moe/Lain-Patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Lain"
version = "auto"
uptodown-dlurl = "https://boorusama.en.uptodown.com/android"

[Canva]
app-name = "Canva"
build-mode = "apk"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
version = "auto"
uptodown-dlurl = "https://canva.en.uptodown.com/android"

[Word]
app-name = "Word"
build-mode = "apk"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
version = "auto"
uptodown-dlurl = "https://microsoft-word-preview.en.uptodown.com/android"

[MobiOffice]
app-name = "MobiOffice- Word, Excel, Slide"
build-mode = "apk"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
version = "auto"
uptodown-dlurl = "https://officesuite-pro-7.en.uptodown.com/android"

[PlantsVsZombies]
app-name = "Plants vs. Zombies FREE"
build-mode = "apk"
patches-source = "MiguelNinja19/miguel-morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "MiguelNinja19"
version = "auto"
uptodown-dlurl = "https://plants-vs-zombies-free.en.uptodown.com/android"

[SDMaidSE]
app-name = "SD Maid SE"
build-mode = "apk"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
version = "auto"
uptodown-dlurl = "https://sd-maid-se.en.uptodown.com/android"

[TeraBox]
app-name = "TeraBox"
build-mode = "apk"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
version = "auto"
uptodown-dlurl = "https://terabox.en.uptodown.com/android"

[Vpnify]
app-name = "vpnify"
build-mode = "apk"
patches-source = "BholeyKaBhakt/android-patches-xtra"
rv-brand = "BholeyKaBhakt"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://vpnify.en.uptodown.com/android"
